# Basic
title: HX
subtitle: HX的开发博客
welcome_message: <a href="https://github.com/lucyDad" target="_blank">我的github地址</a>
description: 欢迎访问.
creator: HX #<a href="http://onev.cat">derk</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: hexiang
    # duoshuo: 
    
# Social
social:
    #weibo: 1687040362/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
    github: lucyDad
    #twitter: hx
    #gplus: 107108267983477358170
    mail: riverfly1987@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
